main_conf:
  run_mode: train
train_conf:
  eval_freq: 100
  log_frequency: 10
  num_folds: 10
  save_smiles_splits: False
  splits_save_path: "save_smiles_splits"
  dataset_type: 'regression'
  loss_function: 'mse'
  num_tasks: 1
  cache_cutoff: 10000
  num_workers: 16
  batch_size: 64
  class_balance: False
  save_folder: "./"
  checkpoint_paths: None
  init_lr: 1e-4
  max_lr: 1e-3
  final_lr: 1e-4
  epochs: 500  # 训练轮数
  warmup_epochs: 2.0
  metrics: ["r2", "rmse", "mae"]
  save_preds: True
  scheduler: NoamLR
  sch_step:
    stage: 4
    gamma: 0.1
  grad_clip: 0
data_conf:
  split_sizes: None
  split_type: 'random'





