defaults:
  - global_conf: default
  - data_conf: default
  - model_conf: default
  - run_conf: default
  - test_conf: default
  - _self_

global_conf:
  seed: 42

model_conf:
  layer:
    depth: 4
    activate: "ReLU"
    norm: False
    hidden_size: 400
    hidden_size_3D: 128
    aggregation: 'mean'
    dropout: 0.0
    ffn_num_layers: 4
    ffn_hidden_size: 400
    bias: False

run_conf:
  train_conf:
    epoch: 500
    batch_size: 64

test_conf:
  test_path: 'data/test_lab.csv'
  threeD_prepath: 'data/3D_canonical_test_lab.npz'
  checkpoint_dir: './'