norm:
  time_norm: False
  max_t: 30
observe_data:
  smi_train_csv_file: 'data/train/canonical_train_1241.csv'
  geom_train_npz_file: 'data/train/3D_canonical_train_1241_rdkit.npz'
  id_columns: ['id']
  smiles_columns: 'smiles'
  target_columns: ['efficiency']
  is_env: True
  env_columns: ['concentration']
  dataset_type: regression
  features_generator: ['rdkit_2d_normalized']
  limit: -1




