norm:
  time_norm: False
  max_t: 30
observe_data:
  n_eval_sections: 0
  val_ratio: 0.0
  smi_train_csv_file: 'data/train/canonical_train_1241.csv'
  geom_train_npz_file: 'data/train/3D_canonical_train_1241.npz'
  id_columns: 'id'
  smiles_columns: 'smiles'
  target_columns: 'efficiency'
  is_env: True
  env_columns: 'concentration'
  dataset_type: 'regression'
  features_generator: 'rdkit_2d_normalized'
#  gdb9_json_file: 'data/gdb9/incons.json'
#  ob_sdf_file: 'data/ob_gdb9/'
#  gbd9_init: random  # random/rdkit
  limit: -1




