layer:
  depth: 4
  activate: "ReLU"
  norm: False
  hidden_size: 400
  hidden_size_3D: 128
  aggregation: 'mean'
  aggregation_norm: 100
  dropout: 0.0
  ffn_num_layers: 4
  ffn_hidden_size: ${layer.hidden_size}
  bias: False
is_env: True
load_checkpoint: False
checkpoint_path: "./"
ensemble_size: 1
loss_function: 'mse'
checkpoint_frzn: None
freeze_first_only: False
number_of_molecules: 1